# Generated by Django 5.1.6 on 2025-03-01 22:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_number', models.CharField(max_length=20, verbose_name='شماره پارکینگ')),
                ('delivery_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ تحویل')),
                ('car_type', models.CharField(max_length=50, verbose_name='نوع خودرو')),
                ('license_plate', models.CharField(max_length=20, verbose_name='شماره انتظامی')),
                ('owner_name', models.CharField(max_length=100, verbose_name='نام مالک')),
                ('engine_number', models.CharField(max_length=50, unique=True, verbose_name='شماره موتور')),
                ('chassis_number', models.CharField(max_length=50, unique=True, verbose_name='شماره شاسی')),
                ('has_cabin_plate', models.BooleanField(default=False, verbose_name='پلاک اتاق')),
                ('registration_number', models.CharField(max_length=20, verbose_name='شماره ثبت')),
                ('acceptance_number', models.CharField(editable=False, max_length=7, unique=True, verbose_name='شماره پذیرش')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پذیرش')),
                ('driver_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی راننده/آورنده')),
                ('driver_license_plate', models.CharField(max_length=20, verbose_name='شماره پلاک راننده/آورنده')),
                ('driver_phone', models.CharField(max_length=15, verbose_name='شماره تماس راننده/آورنده')),
                ('accepted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_entries', to=settings.AUTH_USER_MODEL, verbose_name='مسئول پذیرش')),
            ],
        ),
        migrations.CreateModel(
            name='CarCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قیمت روز')),
                ('fine', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='خلافی')),
                ('fine_document', models.FileField(blank=True, null=True, upload_to='documents/fines/', verbose_name='سند خلافی')),
                ('court_cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='هزینه دادگاهی')),
                ('court_document', models.FileField(blank=True, null=True, upload_to='documents/court/', verbose_name='سند دادگاهی')),
                ('transport_cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='هزینه حمل')),
                ('transport_document', models.FileField(blank=True, null=True, upload_to='documents/transport/', verbose_name='سند حمل')),
                ('proxy_cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='هزینه وکالت')),
                ('proxy_document', models.FileField(blank=True, null=True, upload_to='documents/proxy/', verbose_name='سند وکالت')),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=15, verbose_name='جمع کل')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت هزینه\u200cها')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_costs', to=settings.AUTH_USER_MODEL, verbose_name='مسئول ثبت هزینه\u200cها')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='core.carentry', to_field='acceptance_number', verbose_name='خودرو')),
            ],
        ),
        migrations.CreateModel(
            name='CarParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabin_percentage', models.IntegerField(default=100, verbose_name='درصد اتاق')),
                ('hood', models.BooleanField(default=False, verbose_name='درب موتور')),
                ('radiator', models.BooleanField(default=False, verbose_name='رادیاتور')),
                ('ecu', models.BooleanField(default=False, verbose_name='ایسیو')),
                ('front_rear_doors', models.BooleanField(default=False, verbose_name='درب جلو و عقب')),
                ('wiring', models.BooleanField(default=False, verbose_name='سیم\u200cکشی')),
                ('battery_cable', models.BooleanField(default=False, verbose_name='کابل باطری')),
                ('heater', models.BooleanField(default=False, verbose_name='بخاری')),
                ('suspension_spring', models.BooleanField(default=False, verbose_name='فنر زیر و بند')),
                ('alternator', models.BooleanField(default=False, verbose_name='دینام')),
                ('wiper_motor', models.BooleanField(default=False, verbose_name='موتور برف\u200cپاک\u200cکن')),
                ('rims_tires', models.BooleanField(default=False, verbose_name='رینگ و لاستیک')),
                ('carburetor', models.BooleanField(default=False, verbose_name='کاربراتور')),
                ('starter', models.BooleanField(default=False, verbose_name='استارت')),
                ('gearbox', models.BooleanField(default=False, verbose_name='گیربکس')),
                ('differential', models.BooleanField(default=False, verbose_name='دیفرانسیل')),
                ('distributor_coil', models.BooleanField(default=False, verbose_name='دلکو و کوئل')),
                ('fuel_pump', models.BooleanField(default=False, verbose_name='سیفون بنزین')),
                ('seats', models.BooleanField(default=False, verbose_name='صندلی')),
                ('front_disc', models.BooleanField(default=False, verbose_name='دیسک چرخ جلو')),
                ('battery', models.BooleanField(default=False, verbose_name='باطری')),
                ('steering_box', models.BooleanField(default=False, verbose_name='جعبه فرمان')),
                ('bumpers', models.BooleanField(default=False, verbose_name='سپر عقب و جلو')),
                ('wheel_drum', models.BooleanField(default=False, verbose_name='کاسه چرخ')),
                ('driveshaft_cv', models.BooleanField(default=False, verbose_name='پلوس و گاردان')),
                ('fuel_rail', models.BooleanField(default=False, verbose_name='ریل سوخت')),
                ('trunk_lid', models.BooleanField(default=False, verbose_name='درب صندوق')),
                ('documents', models.BooleanField(default=False, verbose_name='سند')),
                ('injector', models.BooleanField(default=False, verbose_name='انژکتور و سوزن انژکتور')),
                ('glass', models.BooleanField(default=False, verbose_name='شیشه')),
                ('ac', models.BooleanField(default=False, verbose_name='کولر')),
                ('gas_cylinder', models.CharField(choices=[('LNG', 'LNG'), ('CNG', 'CNG'), ('None', 'ندارد')], default='None', max_length=10, verbose_name='کپسول')),
                ('brake_booster', models.BooleanField(default=False, verbose_name='پوستر ترمز')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='وزن')),
                ('plate_status', models.CharField(choices=[('Single', 'تک پلاک'), ('Double', 'جفت پلاک'), ('None', 'فاقد پلاک')], default='None', max_length=20, verbose_name='وضعیت پلاک')),
                ('plate_description', models.TextField(blank=True, verbose_name='توضیحات پلاک')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت قطعات')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='core.carentry', to_field='acceptance_number', verbose_name='خودرو')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_parts', to=settings.AUTH_USER_MODEL, verbose_name='مسئول ثبت قطعات')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
