# Generated by Django 4.2.16 on 2025-03-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_carentry_license_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carentry',
            name='driver_license_plate',
            field=models.CharField(max_length=30, verbose_name='شماره پلاک راننده/آورنده'),
        ),
    ]
