# Generated by Django 5.1.6 on 2025-03-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_carentry_driver_license_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcosts',
            name='recorded_at',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ ثبت هزینه\u200cها'),
        ),
        migrations.AlterField(
            model_name='carentry',
            name='accepted_at',
            field=models.CharField(max_length=10, verbose_name='تاریخ پذیرش'),
        ),
        migrations.AlterField(
            model_name='carentry',
            name='delivery_date',
            field=models.CharField(max_length=10, verbose_name='تاریخ تحویل'),
        ),
        migrations.AlterField(
            model_name='carparts',
            name='recorded_at',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ ثبت قطعات'),
        ),
    ]
