# Generated by Django 5.1.6 on 2025-03-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_carcosts_recorded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carentry',
            name='parking_number',
            field=models.CharField(choices=[('part1', 'part1'), ('part2', 'part2'), ('part3', 'part3'), ('part4', 'part4')], default='None', max_length=10, verbose_name='شمارع پارکینگ'),
        ),
    ]
