# Generated by Django 5.1.6 on 2025-03-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_carentry_parking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carentry',
            name='has_cabin_plate',
            field=models.BooleanField(default=False, verbose_name='پلاکت اتاق'),
        ),
    ]
