# Generated by Django 5.1.6 on 2025-03-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_carentry_has_cabin_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carentry',
            name='parking_number',
        ),
        migrations.RemoveField(
            model_name='carentry',
            name='registration_number',
        ),
        migrations.AlterField(
            model_name='carentry',
            name='has_cabin_plate',
            field=models.BooleanField(default=False, verbose_name='پلاک اتاق'),
        ),
    ]
