# Generated by Django 5.1.6 on 2025-03-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_carentry_parking_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carentry',
            name='parking_number',
            field=models.CharField(default='پارت 1', max_length=20, verbose_name='شماره پارکینگ'),
        ),
        migrations.AlterField(
            model_name='carentry',
            name='acceptance_number',
            field=models.CharField(editable=False, max_length=9, unique=True, verbose_name='شماره پذیرش'),
        ),
    ]
