# Generated by Django 5.1.6 on 2025-03-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_carentry_parking_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carentry',
            name='edited_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ویرایش\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='carentry',
            name='accepted_by',
            field=models.CharField(max_length=100, verbose_name='مسئول پذیرش'),
        ),
        migrations.AlterField(
            model_name='carentry',
            name='parking_number',
            field=models.CharField(max_length=20, verbose_name='شماره پارکینگ'),
        ),
    ]
