# Generated by Django 5.1.6 on 2025-03-07 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_carentry_edited_by_alter_carentry_accepted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_type', models.CharField(choices=[('CAR_ENTRY', 'ویرایش ورود خودرو'), ('CAR_PARTS', 'ویرایش قطعات خودرو'), ('CAR_COSTS', 'ویرایش هزینه\u200cها')], max_length=20, verbose_name='نوع ویرایش')),
                ('edited_at', models.CharField(max_length=10, verbose_name='تاریخ ویرایش')),
                ('car_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='core.carentry', verbose_name='خودرو')),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_logs', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش\u200cکننده')),
            ],
            options={
                'verbose_name': 'لاگ ویرایش',
                'verbose_name_plural': 'لاگ\u200cهای ویرایش',
            },
        ),
    ]
