# Generated by Django 5.1.6 on 2025-03-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_userprofile_national_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'ادمین'), ('regular', 'کاربر معمولی')], default='regular', max_length=10),
        ),
    ]
