# Generated by Django 5.1.6 on 2025-03-09 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_userprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='final_photos/', verbose_name='عکس')),
                ('tracking_code', models.CharField(max_length=50, verbose_name='کد رهگیری')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='نهایی شده')),
                ('finalized_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت نهایی')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_registration', to='core.carentry')),
                ('finalized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
        ),
    ]
