# Generated by Django 5.1.6 on 2025-03-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_finalregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carentry',
            name='car_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع خودرو'),
        ),
        migrations.AlterField(
            model_name='carentry',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره شاسی'),
        ),
        migrations.AlterField(
            model_name='carentry',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ تحویل'),
        ),
        migrations.AlterField(
            model_name='carentry',
            name='driver_license_plate',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره پلاک راننده/آورنده'),
        ),
        migrations.AlterField(
            model_name='carentry',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام و نام خانوادگی راننده/آورنده'),
        ),
        migrations.AlterField(
            model_name='carentry',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس راننده/آورنده'),
        ),
        migrations.AlterField(
            model_name='carentry',
            name='engine_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره موتور'),
        ),
        migrations.AlterField(
            model_name='carentry',
            name='has_cabin_plate',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='پلاکت اتاق'),
        ),
        migrations.AlterField(
            model_name='carentry',
            name='license_plate',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره انتظامی'),
        ),
        migrations.AlterField(
            model_name='carentry',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مالک'),
        ),
        migrations.AlterField(
            model_name='carentry',
            name='parking_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره پارکینگ'),
        ),
    ]
