# Generated by Django 5.1.6 on 2025-03-09 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_carentry_car_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcosts',
            name='car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='core.carentry', to_field='acceptance_number', verbose_name='خودرو'),
        ),
        migrations.AlterField(
            model_name='carcosts',
            name='court_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='هزینه دادگاهی'),
        ),
        migrations.AlterField(
            model_name='carcosts',
            name='daily_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='قیمت روز'),
        ),
        migrations.AlterField(
            model_name='carcosts',
            name='fine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='خلافی'),
        ),
        migrations.AlterField(
            model_name='carcosts',
            name='proxy_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='هزینه وکالت'),
        ),
        migrations.AlterField(
            model_name='carcosts',
            name='transport_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='هزینه حمل'),
        ),
    ]
