# Generated by Django 5.1.6 on 2025-03-11 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_carcosts_car_alter_carcosts_court_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carentry',
            name='chassis_image',
            field=models.FileField(blank=True, null=True, upload_to='car_images/chassis/', verbose_name='عکس شماره شاسی'),
        ),
        migrations.AddField(
            model_name='carentry',
            name='engine_image',
            field=models.FileField(blank=True, null=True, upload_to='car_images/engine/', verbose_name='عکس شماره موتور'),
        ),
        migrations.AddField(
            model_name='carentry',
            name='front_image',
            field=models.FileField(default='car_images/default.jpg', upload_to='car_images/front/', verbose_name='عکس جلوی خودرو'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carentry',
            name='rear_image',
            field=models.FileField(default='car_images/default.jpg', upload_to='car_images/rear/', verbose_name='عکس عقب خودرو'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=True, verbose_name='باید رمز را تغییر دهد'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_number', models.CharField(max_length=50, unique=True, verbose_name='شماره موتور')),
                ('chassis_number', models.CharField(max_length=50, unique=True, verbose_name='شماره شاسی')),
                ('file1', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='فایل ۱')),
                ('file2', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='فایل ۲')),
                ('file3', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='فایل ۳')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('car', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_entry', to='core.carentry', verbose_name='خودرو مرتبط')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
        ),
        migrations.AddField(
            model_name='carentry',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_entry', to='core.document', verbose_name='سند مرتبط'),
        ),
    ]
