# Generated by Django 5.1.6 on 2025-03-13 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_carentry_chassis_image_carentry_engine_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carentry',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_entries', to='core.document', verbose_name='سند مرتبط'),
        ),
        migrations.AlterField(
            model_name='document',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.carentry', verbose_name='خودرو مرتبط'),
        ),
    ]
