# Generated by Django 5.1.6 on 2025-03-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_carentry_document_alter_document_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created_at_gregorian',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ایجاد (میلادی)'),
        ),
        migrations.AlterField(
            model_name='carentry',
            name='acceptance_number',
            field=models.CharField(editable=False, max_length=13, unique=True, verbose_name='شماره پذیرش'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.CharField(blank=True, max_length=10, verbose_name='تاریخ ایجاد'),
        ),
    ]
