# Generated by Django 5.1.6 on 2025-03-21 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_document_created_at_gregorian_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام شرکت')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد شرکت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت\u200cها',
            },
        ),
        migrations.AddField(
            model_name='carcosts',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carentry',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carparts',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='editlog',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finalregistration',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company', verbose_name='شرکت'),
        ),
    ]
