# Generated by Django 5.1.6 on 2025-03-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_company_carcosts_company_carentry_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editlog',
            name='changes',
            field=models.JSONField(blank=True, null=True, verbose_name='تغییرات'),
        ),
    ]
