# Generated by Django 5.1.6 on 2025-03-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='carentry',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره سریال'),
        ),
        migrations.AlterField(
            model_name='carentry',
            name='accepted_by',
            field=models.CharField(max_length=50, verbose_name='مسئول پذیرش'),
        ),
        migrations.AlterField(
            model_name='carentry',
            name='driver_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام و نام خانوادگی راننده/آورنده'),
        ),
        migrations.AlterField(
            model_name='carentry',
            name='edited_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ویرایش\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='carentry',
            name='owner_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام مالک'),
        ),
    ]
