# Generated by Django 5.1.6 on 2025-03-22 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_carentry_physical_readiness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ بازدید اول')),
                ('two_wheeler', models.BooleanField(default=False, verbose_name='دو رکنی')),
                ('two_wheeler_description', models.TextField(blank=True, verbose_name='توضیحات دو رکنی')),
                ('heavy_vehicle_video', models.FileField(blank=True, null=True, upload_to='inspection_videos/', verbose_name='ویدیو خودرو سنگین')),
                ('recorded_at', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ ثبت')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_inspections', to='core.carentry', verbose_name='خودرو')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='شرکت')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'بازدید اول',
                'verbose_name_plural': 'بازدیدهای اول',
            },
        ),
    ]
