# Generated by Django 5.1.6 on 2025-03-22 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_firstinspection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondInspection',
            fields=[
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='second_inspection', serialize=False, to='core.carentry', verbose_name='خودرو')),
                ('second_inspection_date', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ بازدید دوم')),
                ('police_form_scan', models.FileField(blank=True, null=True, upload_to='second_inspection_scans/', verbose_name='اسکن فرم پلیس راهور')),
                ('virtual_plate', models.CharField(blank=True, max_length=20, null=True, verbose_name='پلاک مجازی')),
                ('recorded_at', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ ثبت')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='شرکت')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'بازدید دوم',
                'verbose_name_plural': 'بازدیدهای دوم',
            },
        ),
    ]
