# Generated by Django 5.1.6 on 2025-03-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_carentry_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='carentry',
            name='delivery_date_gregorian',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل (میلادی)'),
        ),
        migrations.AddField(
            model_name='carentry',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
