# Generated by Django 5.1.6 on 2025-03-25 09:26

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_carentry_delivery_date_gregorian_carentry_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcosts',
            name='court_document',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.rename_uploaded_file, verbose_name='سند دادگاهی'),
        ),
        migrations.AlterField(
            model_name='carcosts',
            name='fine_document',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.rename_uploaded_file, verbose_name='سند خلافی'),
        ),
        migrations.AlterField(
            model_name='carcosts',
            name='proxy_document',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.rename_uploaded_file, verbose_name='سند وکالت'),
        ),
        migrations.AlterField(
            model_name='carcosts',
            name='transport_document',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.rename_uploaded_file, verbose_name='سند حمل'),
        ),
        migrations.AlterField(
            model_name='carentry',
            name='chassis_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.rename_uploaded_file, verbose_name='عکس شماره شاسی'),
        ),
        migrations.AlterField(
            model_name='carentry',
            name='engine_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.rename_uploaded_file, verbose_name='عکس شماره موتور'),
        ),
        migrations.AlterField(
            model_name='carentry',
            name='front_image',
            field=models.ImageField(upload_to=core.utils.rename_uploaded_file, verbose_name='عکس جلوی خودرو'),
        ),
        migrations.AlterField(
            model_name='carentry',
            name='rear_image',
            field=models.ImageField(upload_to=core.utils.rename_uploaded_file, verbose_name='عکس عقب خودرو'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_document',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/%Y/%m/%d/', verbose_name='سند شکایت'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file1',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='فایل ۱'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file2',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='فایل ۲'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file3',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='فایل ۳'),
        ),
        migrations.AlterField(
            model_name='firstinspection',
            name='heavy_vehicle_video',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.rename_uploaded_file, verbose_name='ویدیو خودرو سنگین'),
        ),
        migrations.AlterField(
            model_name='secondinspection',
            name='police_form_scan',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.rename_uploaded_file, verbose_name='اسکن فرم پلیس راهور'),
        ),
    ]
