# Generated by Django 5.1.6 on 2025-03-25 20:06

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_carcosts_court_document_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalregistration',
            options={'verbose_name': 'ثبت نهایی', 'verbose_name_plural': 'ثبت\u200cهای نهایی'},
        ),
        migrations.RenameField(
            model_name='finalregistration',
            old_name='finalized_at',
            new_name='recorded_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file1',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file2',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file3',
        ),
        migrations.RemoveField(
            model_name='finalregistration',
            name='is_finalized',
        ),
        migrations.RemoveField(
            model_name='finalregistration',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='finalregistration',
            name='tracking_code',
        ),
        migrations.AddField(
            model_name='carcosts',
            name='recorded_at_gregorian',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ایجاد (میلادی)'),
        ),
        migrations.AddField(
            model_name='carparts',
            name='recorded_at_gregorian',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ایجاد (میلادی)'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='created_at_gregorian',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ایجاد (میلادی)'),
        ),
        migrations.AddField(
            model_name='document',
            name='car_card',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='کارت خودرو'),
        ),
        migrations.AddField(
            model_name='document',
            name='car_document',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='سند خودرو'),
        ),
        migrations.AddField(
            model_name='document',
            name='vekalat',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='وکالت نامه'),
        ),
        migrations.AddField(
            model_name='finalregistration',
            name='police_form_scan',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.rename_uploaded_file, verbose_name='اسکن فرم پلیس راهور'),
        ),
        migrations.AddField(
            model_name='finalregistration',
            name='second_inspection_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ بازدید دوم'),
        ),
        migrations.AddField(
            model_name='finalregistration',
            name='second_inspection_date_gregorian',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ بازدید دوم (میلادی)'),
        ),
        migrations.AddField(
            model_name='finalregistration',
            name='virtual_plate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='پلاک مجازی'),
        ),
        migrations.AddField(
            model_name='firstinspection',
            name='inspection_date_gregorian',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ بازدید اول (میلادی)'),
        ),
        migrations.AlterField(
            model_name='carcosts',
            name='court_cost',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='هزینه دادگاهی'),
        ),
        migrations.AlterField(
            model_name='carcosts',
            name='daily_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='قیمت روز'),
        ),
        migrations.AlterField(
            model_name='carcosts',
            name='fine',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='خلافی'),
        ),
        migrations.AlterField(
            model_name='carcosts',
            name='proxy_cost',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='هزینه وکالت'),
        ),
        migrations.AlterField(
            model_name='carcosts',
            name='total_cost',
            field=models.DecimalField(decimal_places=0, editable=False, max_digits=15, verbose_name='جمع کل'),
        ),
        migrations.AlterField(
            model_name='carcosts',
            name='transport_cost',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='هزینه حمل'),
        ),
        migrations.AlterField(
            model_name='finalregistration',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_registration', to='core.carentry', verbose_name='خودرو'),
        ),
        migrations.DeleteModel(
            name='SecondInspection',
        ),
    ]
