# Generated by Django 5.1.6 on 2025-03-26 08:10

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_finalregistration_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carcosts',
            options={'verbose_name': 'هزینه خودرو', 'verbose_name_plural': 'هزینه\u200cهای خودرو'},
        ),
        migrations.RemoveField(
            model_name='carcosts',
            name='court_cost',
        ),
        migrations.RemoveField(
            model_name='carcosts',
            name='court_document',
        ),
        migrations.RemoveField(
            model_name='carcosts',
            name='fine',
        ),
        migrations.RemoveField(
            model_name='carcosts',
            name='fine_document',
        ),
        migrations.RemoveField(
            model_name='carcosts',
            name='proxy_cost',
        ),
        migrations.RemoveField(
            model_name='carcosts',
            name='proxy_document',
        ),
        migrations.AddField(
            model_name='carcosts',
            name='agahi_cost',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='هزینه آگاهی'),
        ),
        migrations.AddField(
            model_name='carcosts',
            name='agahi_document',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='سند آگاهی'),
        ),
        migrations.AddField(
            model_name='carcosts',
            name='agahi_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('room_replacement', 'اتاق تعویض'), ('engine_replacement', 'موتور تعویض'), ('chassis_replacement', 'شاسی تعویض')], max_length=20), blank=True, null=True, size=3, verbose_name='نوع آگاهی'),
        ),
        migrations.AddField(
            model_name='carcosts',
            name='highway_document',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='سند عوارض آزادراهی'),
        ),
        migrations.AddField(
            model_name='carcosts',
            name='highway_fee',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='کارمزد عوارض آزادراهی'),
        ),
        migrations.AddField(
            model_name='carcosts',
            name='municipal_clearance_fee',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='کارمزد عوارض مفاصا شهرداری'),
        ),
        migrations.AddField(
            model_name='carcosts',
            name='municipal_document',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='سند عوارض مفاصا شهرداری'),
        ),
        migrations.AddField(
            model_name='carcosts',
            name='notary_commitment',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='تعهد محضری'),
        ),
        migrations.AddField(
            model_name='carcosts',
            name='notary_document',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='سند تعهد محضری'),
        ),
        migrations.AddField(
            model_name='carcosts',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='قیمت خرید'),
        ),
        migrations.AddField(
            model_name='carcosts',
            name='signature_document',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='سند گواهی امضا'),
        ),
        migrations.AddField(
            model_name='carcosts',
            name='signature_fee',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='هزینه گواهی امضا'),
        ),
        migrations.AddField(
            model_name='carcosts',
            name='tax_document',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='سند کارمزد مالیات'),
        ),
        migrations.AddField(
            model_name='carcosts',
            name='tax_fee',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='کارمزد مالیات'),
        ),
        migrations.AddField(
            model_name='document',
            name='edited_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ویرایش\u200cکننده'),
        ),
        migrations.AddField(
            model_name='finalregistration',
            name='edited_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ویرایش\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='carcosts',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='carcosts',
            name='recorded_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مسئول ثبت هزینه\u200cها'),
        ),
        migrations.AlterField(
            model_name='carcosts',
            name='transport_cost',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='هزینه حمل و نقل'),
        ),
        migrations.AlterField(
            model_name='carcosts',
            name='transport_document',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='سند حمل و نقل'),
        ),
        migrations.AlterField(
            model_name='carentry',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='carparts',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='carparts',
            name='recorded_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مسئول ثبت '),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.CharField(max_length=10, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مسئول ثبت '),
        ),
        migrations.AlterField(
            model_name='document',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مسئول ثبت '),
        ),
        migrations.AlterField(
            model_name='finalregistration',
            name='finalized_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مسئول ثبت'),
        ),
        migrations.AlterField(
            model_name='firstinspection',
            name='recorded_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مسئول ثبت'),
        ),
    ]
