# Generated by Django 5.1.6 on 2025-03-27 15:39

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_carcosts_options_remove_carcosts_court_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='delivery_date',
            field=models.CharField(default='1111/11/11', max_length=10, verbose_name='تاریخ تحویل'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='delivery_date_gregorian',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل (میلادی)'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_document',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.rename_uploaded_file, verbose_name='سند شکایت'),
        ),
    ]
