# Generated by Django 5.1.6 on 2025-03-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_complaint_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='delivery_date_gregorian',
        ),
        migrations.AddField(
            model_name='document',
            name='delivery_date',
            field=models.CharField(default='1111/11/11', max_length=10, verbose_name='تاریخ تحویل'),
        ),
        migrations.AddField(
            model_name='document',
            name='delivery_date_gregorian',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل (میلادی)'),
        ),
    ]
