# Generated by Django 5.1.6 on 2025-03-27 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_document_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editlog',
            name='car_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_logs', to='core.carentry', verbose_name='خودرو'),
        ),
    ]
