# Generated by Django 5.1.6 on 2025-03-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_editlog_car_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='deceased_doc1',
            field=models.ImageField(blank=True, null=True, upload_to='deceased_docs/', verbose_name='مدرک فوتی ۱'),
        ),
        migrations.AddField(
            model_name='document',
            name='deceased_doc2',
            field=models.ImageField(blank=True, null=True, upload_to='deceased_docs/', verbose_name='مدرک فوتی ۲'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_deceased',
            field=models.BooleanField(default=False, verbose_name='فوتی'),
        ),
    ]
