# Generated by Django 5.1.6 on 2025-03-31 21:20

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_document_company_paper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carentry',
            name='serial_number',
        ),
        migrations.CreateModel(
            name='Serialnumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره سریال')),
                ('Registration_nnhk', models.ImageField(upload_to=core.utils.rename_uploaded_file, verbose_name='عکس جلوی خودرو')),
                ('recorded_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='برگه ثبت نام nnhk ')),
                ('recorded_at', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ ثبت شماره سریال')),
                ('recorded_at_gregorian', models.DateField(blank=True, null=True, verbose_name='تاریخ ثبت (میلادی)')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='serial', to='core.carentry', to_field='acceptance_number', verbose_name='خودرو')),
            ],
        ),
    ]
