# Generated by Django 5.1.6 on 2025-04-03 03:23

import core.utils
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_carentry_serial_number_serialnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstinspection',
            name='Diagnosis_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('room_replacement', 'اتاق تعویض'), ('engine_replacement', 'موتور تعویض'), ('chassis_replacement', 'شاسی تعویض')], max_length=20), blank=True, null=True, size=3, verbose_name='نوع آگاهی'),
        ),
        migrations.AddField(
            model_name='firstinspection',
            name='accept',
            field=models.BooleanField(default=False, verbose_name='تایید'),
        ),
        migrations.AddField(
            model_name='firstinspection',
            name='agahi_report',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.rename_uploaded_file, verbose_name='استعلام آگاهی'),
        ),
        migrations.AddField(
            model_name='firstinspection',
            name='comment_exit',
            field=models.TextField(blank=True, verbose_name='علت خروج'),
        ),
        migrations.AddField(
            model_name='firstinspection',
            name='exit',
            field=models.BooleanField(default=False, verbose_name='خروج از چرخه'),
        ),
    ]
