# Generated by Django 5.1.6 on 2025-04-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_firstinspection_police_form_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='carentry',
            name='car_color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='carentry',
            name='car_system',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='سیستم'),
        ),
    ]
