# Generated by Django 5.1.6 on 2025-04-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_carentry_car_color_carentry_car_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='National_ID',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه ملی'),
        ),
    ]
